ci(elements): add step to check for elements config changes

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -57,7 +57,13 @@ jobs:
             npm run build:i18n
             npm run test:i18n:dist
       - name: Build Elements
-        run: npm run build:elements
+        run: npm run elements:configure && npm run build:elements
+      - name: Check for Elements config changes
+        run: |
+            if [ -n "$(git status --porcelain -- projects/igniteui-angular-elements/**/elements.config.ts)" ]; then
+                echo "Error: There are changes to the Elements config. Run `npm run elements:configure` and commit." >&2
+                exit 1
+            fi
       - name: Test Elements
         run: npm run test:elements
       - name: Bundle Tree-Shake & SSR Test
